name: deploy

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Get credentials
        run: |-
          gcloud container clusters get-credentials ${{ secrets.GCP_CLUSTER }} \
            --zone ${{ secrets.GCP_ZONE }} \
            --project ${{ secrets.GCP_PROJECT_ID }}
      - name: Deploy
        run: |-
          IMAGE_TAG=$(echo $GITHUB_REF | cut -d / -f 3)
          helm upgrade \
            --atomic \
            --install \
            --namespace http-quest \
            --set image.tag=${IMAGE_TAG} \
            --set secrets.BUGSNAG_API_KEY=${{ secrets.BUGSNAG_API_KEY }} \
            http-quest \
            ./charts/http-quest/
